config/routes.rb
BirdDog::Application.routes.draw do
  devise_for  :users,
              :controllers => {
                :registrations => 'users'
              }
              
  devise_scope :user do
    resources :users, :only => [:index]
    get "login", :to => "devise/sessions#new"
    get "sign_up", :to => "users#new"
    get "logout", :to => "devise/sessions#destroy"
  end

  root :to => 'home#index'

  resources :properties do
    member do
      post :add_comparable
    end
  end
  resources :streets
  resources :hunts do
    member do 
      post :add_by_url
    end
    collection do  
      post :add_property
      post :add_street
    end
  end
  resources :hunt_streets, only: [:new, :create]

 

end

app/models/hunt.rb
class Hunt < ActiveRecord::Base
  attr_accessible :name, :status, :user_id, :aquisition_strategy, :target_location, :goal, :price_max, :price_min, :target_purchase_discount_percent, :target_rent_weekly, :down_payment_percent, :interest_rate_annual, :origination_fee, :stamp_duty_rate, :closing_costs_misc_fee, :vacancyloss_percent, :accounting, :advertising, :bankcharges, :electricity, :gas, :home_owner_association_fees, :insurance_hazard, :insurance_mortgage, :landscape_maintenance, :legal, :maintenance, :property_management_percent, :miscellaneous_fee, :permits, :pest_termite_control, :phone, :postage, :referrals_commissions, :reserves, :supplies_maintenance, :supplies_office, :taxes_property, :warranties, :water_sewer

  belongs_to :user

  has_many :hunt_properties
  has_many :properties, :through => :hunt_properties

  has_many :hunt_streets
  has_many :streets, :through => :hunt_streets
end

app/controllers/hunts_controller.rb
class HuntsController < ApplicationController

  before_filter :authenticate_user!

  def index
    @hunts = current_user.hunts
    @hunts_properties = hunt_select(:properties)
    @hunts_streets = hunt_select(:streets)
  end

  def new
    @hunt = Hunt.new
  end

  def create
    @hunt = current_user.hunts.new(params[:hunt])
    if @hunt.save
      redirect_to hunts_path, notice: 'Hunt was successfully created!'
    else
      flash.now[:alert] = 'Hunt was NOT created!'
      render :new
    end
  end

  def show
    @hunt = Hunt.find(params[:id])
    @hunts_streets = hunt_select(:streets)
    
    # @properties = @hunt.properties
  end

  def edit
    @hunt = Hunt.find(params[:id])
  end

  def update
    @hunt = Hunt.find(params[:id])
    if @hunt.update_attributes(params[:hunt])
      redirect_to @hunt, notice: 'Hunt was successfully updated!'
    else
      render :edit
      flash.now[:alert] = 'Hunt was NOT updated!'
    end
  end

  def destroy
    @hunt = Hunt.find(params[:id])
    @hunt.destroy
    redirect_to hunts_path
  end

  def add_street
    hunt = Hunt.find params[:hunt_id]
    params[:ids].each do |street_id|
      @hunt_street= HuntStreet.create({
        hunt_id: params[:hunt_id],
        street_id: street_id
      })
    end

    render nothing: true
  end 

  def add_property
    hunt = Hunt.find params[:hunt_id]
    params[:ids].each do |property_id|
      @hunt_property = HuntProperty.create({
        hunt_id: params[:hunt_id],
        property_id: property_id
      })
    end

    render nothing: true
  end 

  def add_by_url
    @property = Property.find_by_details_url params["url"]
    @hunt = Hunt.find(params[:id])
    if @property
      begin
        @hunt.properties << @property
        flash[:notice] = 'added'
      rescue ActiveRecord::RecordInvalid
        flash[:notice] = "already in hunt"
      end
      redirect_to hunt_path(@hunt)
    else
      handle_new_property_url
    end
  end


private
 
  def handle_new_property_url
    # in future see if url domain is supoorted for scraping
    # for now, just redirect to new property form


    # redirect to form toeh action that loads the properties new form
    new_prop_params = {
      hunt_id: params[:id],
      details_url: params[:url]
    }
    redirect_to new_property_url(new_prop_params)

    # other functions to build could be to test for harvested domain and redirect to importio to tune up a connector
    # other function could be to serve the user a list of domains which need tuning
    
  end


  def hunt_select(which = nil)
    function_name = ["hunt", which.to_s].join("_")
    current_user.hunts.map do |hunt|
      #this will either hunt_properties or hunt_streets
      # think hunt.hunt_properties || hunt.hunt_streets
      hunt.send(function_name) 
    end.flatten.uniq_by{ |obj| obj.hunt_id}
  end
end

app/helpers/hunts_helper.rb
module HuntsHelper
  def get_json_for_hunts hunts_streets
    streets_array = hunts_streets.map do |hs|
      hs.hunt.streets.map do |street|
        street
      end
    end.flatten.to_json

  end
end

app/views/hunts/_form.html.haml
= field_set_tag 'Hunt Details' do
  .form-horizontal
    = form_for @hunt do |f|
      .col-md-4
        .form-group
          = positive_button_submit_tag
        .form-group
          .col-md-4
            = f.label :name
          .col-md-8
            = f.text_field :name
        .form-group
          .col-md-4
            = f.label :target_location
          .col-md-8
            = f.text_field :target_location, placeholder: 'London, Rome, etc.'
      .col-md-1
      .col-md-3
        .form-group
          .col-md-4
            = f.label :status
          .col-md-8
            = f.select :status, options_for_select(["Active", "Stand-by"], @status)
        .form-group
          .col-md-4
            = f.label :goal
          .col-md-8
            = f.select :goal, options_for_select(["Vacation Home", "Residential Portfolio", "Commercial Portfolio", "Parking Portfolio"], "Residential Portfolio")
      .col-md-4
        .form-group
          .col-md-4
            = f.label :aquisition_strategy
          .col-md-8
            = f.select :aquisition_strategy, options_for_select(["Buy & Hold", "Flip", "Renovate", "Joint Venture"], "Buy & Hold")
      .col-md-12
        %h3 Further Details
        %hr
      .col-md-6
        %h4 Core Financial Assumptions:
        %hr
        .form-group
          .col-md-6
            = f.label "Max price"
          .col-md-6
            = f.number_field :price_max
        .form-group
          .col-md-6
            = f.label "Min price"
          .col-md-6
            = f.number_field :price_min
        .form-group
          .col-md-6
            = f.label "Target purchase discount (%)"
          .col-md-6
            = f.number_field :target_purchase_discount_percent
        .form-group
          .col-md-6
            = f.label "Target weekly rent"
          .col-md-6
            = f.number_field :target_rent_weekly
        .form-group
          .col-md-6
            = f.label "Down payment percent"
          .col-md-6
            = f.number_field :down_payment_percent
        .form-group
          .col-md-6
            = f.label 'Annual interest rate'
          .col-md-6
            = f.number_field :interest_rate_annual
      .col-md-6
        %h4 Fee Assumptions:
        %hr
        .form-group
          .col-md-6
            = f.label :origination_fee
          .col-md-6
            = f.number_field :origination_fee
        .form-group
          .col-md-6
            = f.label :stamp_duty_rate
          .col-md-6
            = f.number_field :stamp_duty_rate
        .form-group
          .col-md-6
            = f.label :closing_costs_misc_fee
          .col-md-6
            = f.number_field :closing_costs_misc_fee
        .form-group
          .col-md-6
            = f.label 'Vacancy Loss (%)'
          .col-md-6
            = f.number_field :vacancyloss_percent
        .form-group
          .col-md-6
            = f.label :accounting
          .col-md-6
            = f.number_field :accounting
        .form-group
          .col-md-6
            = f.label :advertising
          .col-md-6
            = f.number_field :advertising
        .form-group
          .col-md-6
            = f.label :bankcharges
          .col-md-6
            = f.number_field :bankcharges
      .col-md-12
        %h4 Running Costs:
        %hr
        .col-md-4
          .form-group
            .col-md-6
              = f.label :electricity
            .col-md-6
              = f.number_field :electricity
          .form-group
            .col-md-6
              = f.label :gas
            .col-md-6
              = f.number_field :gas
          .form-group
            .col-md-6
              = f.label :home_owner_association_fees
            .col-md-6
              = f.number_field :home_owner_association_fees
          .form-group
            .col-md-6
              = f.label :insurance_hazard
            .col-md-6
              = f.number_field :insurance_hazard
          .form-group
            .col-md-6
              = f.label :insurance_mortgage
            .col-md-6
              = f.number_field :insurance_mortgage
          .form-group
            .col-md-6
              = f.label :status
            .col-md-6
              = f.number_field :status
          .form-group
            .col-md-6
              = f.label :landscape_maintenance
            .col-md-6
              = f.number_field :landscape_maintenance
          .form-group
            .col-md-6
              = f.label :legal
            .col-md-6
              = f.number_field :legal
        .col-md-4
          .form-group
            .col-md-6
              = f.label :maintenance
            .col-md-6
              = f.number_field :maintenance
          .form-group
            .col-md-6
              = f.label :property_management_percent
            .col-md-6
              = f.number_field :property_management_percent
          .form-group
            .col-md-6
              = f.label :permits
            .col-md-6
              = f.number_field :permits
          .form-group
            .col-md-6
              = f.label :miscellaneous_fee
            .col-md-6
              = f.number_field :miscellaneous_fee
          .form-group
            .col-md-6
              = f.label :pest_termite_control
            .col-md-6
              = f.number_field :pest_termite_control
          .form-group
            .col-md-6
              = f.label :phone
            .col-md-6
              = f.number_field :phone
          .form-group
            .col-md-6
              = f.label :postage
            .col-md-6
              = f.number_field :postage
        .col-md-4
          .form-group
            .col-md-6
              = f.label :referrals_commissions
            .col-md-6
              = f.number_field :referrals_commissions
          .form-group
            .col-md-6
              = f.label :reserves
            .col-md-6
              = f.number_field :reserves
          .form-group
            .col-md-6
              = f.label :supplies_maintenance
            .col-md-6
              = f.number_field :supplies_maintenance
          .form-group
            .col-md-6
              = f.label :permits
            .col-md-6
              = f.number_field :permits
          .form-group
            .col-md-6
              = f.label :supplies_office
            .col-md-6
              = f.number_field :supplies_office
          .form-group
            .col-md-6
              = f.label :taxes_property
            .col-md-6
              = f.number_field :taxes_property
          .form-group
            .col-md-6
              = f.label :warranties
            .col-md-6
              = f.number_field :warranties
          .form-group
            .col-md-6
              = f.label :water_sewer
            .col-md-6
              = f.number_field :water_sewer











          



  
   
      


   

app/views/hunts/_hunt_show_cost.html.haml
%table.table.table-striped
  %tr
    %th Electricity
    %td=@hunt.electricity
  %tr
    %th Gas
    %td=@hunt.gas
  %tr
    %th Home owner association fees
    %td=@hunt.home_owner_association_fees
  %tr
    %th Insurance hazard
    %td=@hunt.insurance_hazard
  %tr
    %th Insurance mortgage
    %td=@hunt.insurance_mortgage
  %tr
    %th Landscape maintenance
    %td=@hunt.landscape_maintenance
  %tr
    %th Legal
    %td=@hunt.legal
  %tr
    %th Maintenance
    %td=@hunt.maintenance
  %tr
    %th Property management percent
    %td=@hunt.property_management_percent
  %tr
    %th Miscellaneous fee
    %td=@hunt.miscellaneous_fee
  %tr
    %th Permits
    %td=@hunt.permits
  %tr
    %th Pest termite control
    %td=@hunt.pest_termite_control
  %tr
    %th Phone
    %td=@hunt.phone
  %tr
    %th Postage
    %td=@hunt.postage
  %tr
    %th Referrals commissions
    %td=@hunt.referrals_commissions
  %tr
    %th Reserves
    %td=@hunt.reserves
  %tr
    %th Supplies maintenance
    %td=@hunt.supplies_maintenance
  %tr
    %th Supplies office
    %td=@hunt.supplies_office
  %tr
    %th Taxes property
    %td=@hunt.taxes_property
  %tr
    %th Warranties
    %td=@hunt.warranties
  %tr
    %th Water sewer
    %td=@hunt.water_sewer

app/views/hunts/_hunt_show_detail.html.haml
%table.table.table-striped
  %tr
    %th Name
    %td=@hunt.name
  %tr
    %th Status
    %td=@hunt.status                     
  %tr
    %th Target location
    %td=@hunt.target_location
  %tr
    %th Goal
    %td=@hunt.goal
  %tr
    %th Aquisition Strategy
    %td=@hunt.aquisition_strategy  
  

app/views/hunts/_hunt_show_fee.html.haml
%table.table.table-striped
 %tr
  %th Origination fee
  %td=@hunt.origination_fee
 %tr
  %th Stamp duty rate
  %td=@hunt.stamp_duty_rate
 %tr
  %th Closing costs misc fee
  %td=@hunt.closing_costs_misc_fee
 %tr
  %th Vacancy loss (%)
  %td=@hunt.vacancyloss_percent
 %tr
  %th Accounting
  %td=@hunt.accounting
 %tr
  %th Advertising
  %td=@hunt.advertising
 %tr
  %th Bankcharges
  %td=@hunt.bankcharges

app/views/hunts/_hunt_show_finance.html.haml
%table.table.table-striped
  %tr
    %th Max price
    %td=@hunt.price_max
  %tr
    %th Min price
    %td=@hunt.price_min
  %tr
    %th Target purchase discount
    %td=@hunt.target_purchase_discount_percent
  %tr
    %th Target weekly rent
    %td=@hunt.target_rent_weekly
  %tr
    %th Down payment percent
    %td=@hunt.down_payment_percent
  %tr
    %th Annual interest rate
    %td=@hunt.interest_rate_annual

app/views/hunts/_hunt_show_props.html.haml
%table.table.table-striped
  %tr
    %th Price
    %th Beds
    %th Location
  - @hunt.properties.each do |property|
    %tr
      %td=number_to_currency(property.price, :unit => "£", :precision => 0)
      %td=property.num_bedrooms
      %td=link_to property.displayable_address, property_path(property.id)

app/views/hunts/_hunt_show_st.html.haml
%table.table.table-striped
  %tr
    %th Name
    %th Postcode
  - @hunt.streets.each do |street|
    %tr
      %td=street.name
      %td=street.postcode
      

app/views/hunts/_hunt_table.html.haml
%table.table.table-striped
  %tr
    %th name
    %th
    
  - hunts.each do |hunt|
    %tr  
      %td
        =hunt.hunt.name
        %ul
          - hunt.hunt.properties.each do |property|
            %li= property.property_source_id

app/views/hunts/_hunts_properties_table.html.haml
%table.table.table-striped
  %tr
    %th Hunt Name & List of Linked Properties
    %th
  - @hunts_properties.each do |hunt|
    %tr  
      %td
        =hunt.hunt.name
        %ul
          - hunt.hunt.properties.each do |property|
            %li
              = number_to_currency(property.price, :unit => "£", :precision => 0)
              .horizontal_spacer
              - if property.num_bedrooms
                = property.num_bedrooms
                Beds
              .horizontal_spacer
              = link_to property.displayable_address, property_path(property.id)

app/views/hunts/_hunts_streets_table.html.haml
%table.table.table-striped
  %tr
    %th Hunt Name & List of Linked Streets
    %th
  - @hunts_streets.each do |hunt|
    %tr  
      %td
        =hunt.hunt.name
        %ul
          - hunt.hunt.streets.each do |street|
            %li
              = street.postcode
              .horizontal_spacer
              -if street.name
                = street.name
              
      

app/views/hunts/edit.html.haml
=button_link_to 'Show', @hunt
=button_link_to 'Back', hunts_path
=render 'form'

app/views/hunts/index.html.haml
.col-md-8
.col-md-4
  = big_button_link_to 'Add Hunt', new_hunt_path

%ul.nav.nav-tabs
  %li.active
    %a{"data-toggle" => "tab", href: "#all_hunts"} All Hunts
  %li
    %a{"data-toggle" => "tab", href: "#hunt_properties"}  Property Hunts
  %li
    %a{"data-toggle" => "tab", href: "#hunt_streets"} Street Hunts
.tab-content
  #all_hunts.tab-pane.active
    %table.table.table-striped
      %tr
        %th name
        %th
        
      - @hunts.each do |hunt|
        %tr  
          %td=hunt.name
          %td
            =button_group do
              =button_link_to "Show", hunt
              =button_link_to "Edit", edit_hunt_path(hunt)
              =negative_button_link_to "Destroy", hunt, :confirm => 'Are you sure?', :method => :delete
  #hunt_properties.tab-pane
    = render partial: "hunts_properties_table"
  #hunt_streets.tab-pane
    = render partial: "hunts_streets_table"

app/views/hunts/new.html.haml
.col-md-8
.col-md-4
  =button_link_to 'Back to Hunt', hunts_path
=render 'form'

app/views/hunts/show.html.haml
.col-md-7
  =button_group do
    =button_link_to "Edit", edit_hunt_path
    =negative_button_link_to "Destroy", @hunt, :confirm => 'Are you sure?', :method => :delete
.col-md-5
  = form_tag add_by_url_hunt_path(@hunt), method: :post do 
    = url_field_tag :url
    = positive_button_submit_tag 'Add a Property URL'
.col-md-12
  %ul.nav.nav-tabs
    %li.active
      %a{"data-toggle" => "tab", href: "#detail"} Core Details
    %li
      %a{"data-toggle" => "tab", href: "#finance"} Financials
    %li
      %a{"data-toggle" => "tab", href: "#fee"} Fee Assumptions
    %li
      %a{"data-toggle" => "tab", href: "#cost"} Running Costs
    - if @hunt.properties
      %li
        %a{"data-toggle" => "tab", href: "#props"} Properties
    - if @hunt.streets
      %li
        %a{"data-toggle" => "tab", href: "#st"} Streets
  .tab-content
    #detail.tab-pane.active
      = render partial: 'hunt_show_detail'
    #finance.tab-pane
      = render partial: 'hunt_show_finance'
    #fee.tab-pane
      = render partial: 'hunt_show_fee'
    #cost.tab-pane
      = render partial: 'hunt_show_cost'
    - if @hunt.properties
      #props.tab-pane
        = render partial: 'hunt_show_props'
    - if @hunt.streets
      #st.tab-pane
        = render partial: 'hunt_show_st'
   




     