config/routes.rb
BirdDog::Application.routes.draw do
  devise_for  :users,
              :controllers => {
                :registrations => 'users'
              }
              
  devise_scope :user do
    resources :users, :only => [:index]
    get "login", :to => "devise/sessions#new"
    get "sign_up", :to => "users#new"
    get "logout", :to => "devise/sessions#destroy"
  end

  root :to => 'home#index'

  resources :properties do
    member do
      post :add_comparable
    end
  end
  resources :streets
  resources :hunts do
    member do 
      post :add_by_url
    end
    collection do  
      post :add_property
      post :add_street
    end
  end
  resources :hunt_streets, only: [:new, :create]

 

end

app/models/street.rb
class Street < ActiveRecord::Base
  attr_accessible :name, :postcode, :image_capture, :longitude, :latitude, :city, :state, :postal_cod

  has_many :hunt_streets
  has_many :hunts, :through => :hunt_streets

  mount_uploader :image_capture, ImageUploader

  before_save :extract_geolocation
 
  def extract_geolocation
    img = Magick::Image.read(image_capture.file.file)[0] rescue nil
    
    return unless img
    img_lat = img.get_exif_by_entry('GPSLatitude')[0][1].split(', ') rescue nil
    img_lng = img.get_exif_by_entry('GPSLongitude')[0][1].split(', ') rescue nil
    
 
    lat_ref = img.get_exif_by_entry('GPSLatitudeRef')[0][1] rescue nil
    lng_ref = img.get_exif_by_entry('GPSLongitudeRef')[0][1] rescue nil
 
    return unless img_lat && img_lng && lat_ref && lng_ref
 
    latitude = to_frac(img_lat[0]) + (to_frac(img_lat[1])/60) + (to_frac(img_lat[2])/3600)
    longitude = to_frac(img_lng[0]) + (to_frac(img_lng[1])/60) + (to_frac(img_lng[2])/3600)
 
    latitude = latitude * -1 if lat_ref == 'S'  # (N is +, S is -)
    longitude = longitude * -1 if lng_ref == 'W'   # (W is -, E is +)
    
    self.latitude = latitude
    self.longitude = longitude

    if geo = Geocoder.search("#{latitude},#{longitude}").first
      self.city = geo.city
      # self.state = geo.state
      self.postcode = geo.postal_code
    end
    
  end
 
  def to_frac(strng)
    numerator, denominator = strng.split('/').map(&:to_f)
    denominator ||= 1
    numerator/denominator
  end


end

app/controllers/streets_controller.rb
class StreetsController < ApplicationController

  before_filter :authenticate_user!
  
  def index
    @streets = Street.all
    @hunts = current_user.hunts
  end

  def new
    @street = Street.new
  end

  def create
    @street = Street.new(params[:street])
    if @street.save
      redirect_to @street, notice: 'Street was successfully created!'
    else
      flash.now[:alert] = 'Street was NOT created!'
      render :new
    end
  end

  def show
    @street = Street.find(params[:id])
  end

  def edit
    @street = Street.find(params[:id])
  end

  def update
    @street = Street.find(params[:id])
    if @street.update_attributes(params[:street])
      redirect_to @street, notice: 'Street was successfully updated!'
    else
      render :edit
      flash.now[:alert] = 'Street was NOT updated!'
    end
  end

  def destroy
    @street = Street.find(params[:id])
    @street.destroy
    redirect_to streets_path
  end

end

app/views/streets/_form.html.haml
= field_set_tag 'Street Details' do
  .form-horizontal
    = form_for @street do |f|
      .col-md-2
        .form-group
          = positive_button_submit_tag
      .col-md-5
        .form-group
          .col-md-3
            = f.label "Let's call it..."
          .col-md-9
            = f.text_field :name, placeholder: 'Wow, what a great street...'
        .form-group
          .col-md-3
            = f.label :postcode
          .col-md-9
            = f.text_field :postcode, placeholder: 'EC1, N1 8AF...'
        .row
          .form-group
            .col-md-5
              = f.label 'Image captured on Location'
            .col-md-7
              = f.file_field :image_capture

app/views/streets/edit.html.haml
=render 'form'

app/views/streets/index.html.haml
.col-md-7
  
.table_list.col-md-5
  = select_tag :hunt_id, options_from_collection_for_select(@hunts, "id", "name")
  = add_button_tag "Add Checked to a Hunt", id: "submit_hunt_street_selection"
  

%table.table.table-striped#data_table
  %thead
    %tr
      %th Postcode
      %th Picture (if provided)
      %th
  %tbody
    - @streets.each do |street|
      %tr  
        %td
          = check_box :street_select_checkbox, street.id,
          {class: "street_checkbox", "data-street-id" => street.id}
          = street.postcode
        %td= image_tag street.image_capture.thumb if street.image_capture? 

        %td
          =button_group do
            =button_link_to "Show", street
            =button_link_to "Edit", edit_street_path(street)
            =negative_button_link_to "Destroy", street, :confirm => 'Are you sure?', :method => :delete

app/views/streets/new.html.haml
=button_link_to 'Back to Streets', streets_path
=render 'form'

app/views/streets/show.html.haml
.col-md-6
  %table.table.table-striped
    %tr
      %th
        Name
      %td
        = @street.name
    %tr
      %th
        Postcode
      %td
        = @street.postcode
.col-md-5
  #map-street

.row
  .col-md-1
  .property-show.col-md-10
    - if @street.image_capture?
      = image_tag @street.image_capture.standard
  .col-md-1


:javascript
  window.street = #{@street.postcode.to_json}