config/routes.rb
BirdDog::Application.routes.draw do
  devise_for  :users,
              :controllers => {
                :registrations => 'users'
              }
              
  devise_scope :user do
    resources :users, :only => [:index]
    get "login", :to => "devise/sessions#new"
    get "sign_up", :to => "users#new"
    get "logout", :to => "devise/sessions#destroy"
  end

  root :to => 'home#index'

  resources :properties do
    member do
      post :add_comparable
    end
  end
  resources :streets
  resources :hunts do
    member do 
      post :add_by_url
    end
    collection do  
      post :add_property
      post :add_street
    end
  end
  resources :hunt_streets, only: [:new, :create]

 

end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title BirdDog
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = javascript_include_tag raw "https://maps.googleapis.com/maps/api/js?key=#{ENV['GOOGLE_SIMPLE_KEY']}&sensor=false"
    = csrf_meta_tags

  %body
    %nav.navbar.navbar-default.navbar-static-top{role: "navigation"}
      .navbar-header
        %button.navbar-toggle{"data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", type: "button"}
          %span.sr-only Toggle navigation
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        %a.navbar-brand{href: "/"}
          .logo=image_tag "logo.png"
      %ul.nav.navbar-nav.navbar-right
        - if user_signed_in? == false
          %li
            =link_to "Sign-up", sign_up_path
        - if user_signed_in?
          %li
            =link_to 'My Hunts', hunts_path
          %li
            =link_to '+Hunt', new_hunt_path
          %li
            =link_to '+Property', new_property_path
          %li
            =link_to '+Street', new_street_path
          %li.dropdown
            %a.dropdown-toggle{"data-toggle" => "dropdown", href: "#"}
              My Library
              %b.caret
            %ul.dropdown-menu
              %li
                =link_to 'Property Library', properties_path
              %li
                =link_to 'Street Library', streets_path
          %li.dropdown
            %a.dropdown-toggle{"data-toggle" => "dropdown", href: "#"}
              My Account
              %b.caret
            %ul.dropdown-menu
              %li
                =link_to 'Project::Bird_Dog', root_path
              %li
                =link_to 'Evernote-', root_path
              %li
                =link_to 'Importio-', root_path
              %li
                =link_to 'Google-', root_path
              %li
                =link_to 'Duedil-', root_path
              %li.divider
              %li
                =link_to 'Logout', logout_path

    .container  
      - flash.each do |key, value|
        %div{class: flash_class(key)}
          = value
      .row
        - if user_signed_in?
          .col-md-1
            .tablet
              - menu_pages.each do |page|
                -if current_path == page[1]
                  %a.menu-item.selected{href: page[1], id:page[0]}
                    .menu-icon
                    .menu-text= page[0]
                - else
                  %a.menu-item{href: page[1], id:page[0]}
                    .menu-icon
                    .menu-text= page[0]
        .col-md-11
          = yield

    .footer.navbar.navbar-default.navbar-static-bottom
    
      
      